version: '3.8'
services:
  db:
    container_name: pgDbDesafio9
    image: postgres:13.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "docker"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "gostack_desafio09"
    ports:
      - "5432:5432"
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
